<a href="https://colab.research.google.com/github/ypanjwani/Deep-Learning/blob/main/Deep_Learning_Lec_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf

#rank 0
scalar=tf.constant(7)
print("Scaler :", scalar)

#rank 1
vector=tf.constant([1,2,3])
print("vector :", vector)

#rank 2
matrix=tf.constant([[1, 2], [3, 4]])
print("Matrix :", matrix)

tensor3d=tf.constant([[[1], [2]], [[3], [4]]])
print("Tensor 3d :", tensor3d)

Scaler : tf.Tensor(7, shape=(), dtype=int32)
vector : tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix : tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor 3d : tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
